name: CI Pipeline

on:
  push:
    branches: [devops-pipelines]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'devops-js-mastery/devops-pipelines/package-lock.json'

      - name: Install Dependencies
        working-directory: 'devops-js-mastery/devops-pipelines/'
        run: npm install

      - name: Run Tests
        run: npm test